# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEOKLbM6w1eEpnIgh0b1NpoeEVtHyQpz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Data preparation and manipulation script"""

def plot_binary_feature(dataset, feature):
    feature_mapping = {0: 'No', 1: 'Yes'}
    feature_counts = dataset[f"{feature}"].map(feature_mapping).value_counts()

    feature_counts.plot(kind = 'bar')
    plt.xlabel(f"{feature}")
    plt.ylabel('Count')
    plt.title(f"Distribution of {feature}")
    plt.xticks(rotation = 0)
    plt.show()

def plot_categorical_feature(dataset, feature, mapping_categories):
    feature_mapping = {}
    for n in range(len(mapping_categories)):
        feature_mapping[n] = mapping_categories[n]

    feature_counts = dataset[f"{feature}"].map(feature_mapping).value_counts()

    feature_counts.plot(kind = 'bar')
    plt.xlabel(f"{feature}")
    plt.ylabel('Count')
    plt.title(f"Distribution of {feature}")
    plt.xticks(rotation = 0)
    plt.show()

def plot_histogram_feature(dataset, feature, bins = 'fd'):
    plt.hist(dataset[f"{feature}"], bins = bins)
    plt.xlabel(f"{feature}")
    plt.ylabel('Count')
    plt.title(f"Distribution of {feature}")
    plt.xticks(rotation = 0)
    plt.show()

